config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'
  get   'users/profile'             => 'users#show'
  patch 'users/profile'             => 'users#update'
  get   'users/account'             => 'users#account'
  get   'rooms/post'                => 'rooms#show_rooms'
  get   'rooms/search'              => 'rooms#search'
  post  'reservations/confirm(/id)' => 'rooms#confirm'
  post  'reservations/back'         => 'rooms#back'
  post  'reservations/complete'     => 'rooms#complete'
  get   '/reservations'             => 'rsrvs#show'

  devise_for :users, :controllers => {
    :registrations  => 'users/registrations',
    :sessions       => 'users/sessions'   
  } 
  
  resources :rooms

end

app/views/shared/_aside.html.erb
  <aside>
    <ul>
      <% if controller.controller_name == "users" && controller.action_name == "account" %>
        <li class = "open-page">
          <%= link_to "アカウント", users_account_path %>
        </li>
        <li>
          <%= link_to "プロフィール", users_profile_path %>
        </li>
      <% elsif controller.controller_name == "users" && (controller.action_name == "show" || controller.action_name == "update") %>
        <li>
          <%= link_to "アカウント", users_account_path %>
        </li>
        <li class = "open-page">
          <%= link_to "プロフィール", users_profile_path %>
        </li>
      <% elsif controller.controller_name == "rooms" && controller.action_name == "new" %>
        <li class = "open-page">
          <%= link_to "基本情報", new_room_path %>
        </li>
      <% end %>
    </ul>
  </aside>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div id = "error_explanation">
    <% obj.errors.full_messages.each do |message| %>
      <ul>
        <li class= "err-alart"><%= message %></li>
      </ul>
    <% end %>
  </div>
<% end %>