config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'
  get   'users/profile'             => 'users#show'
  patch 'users/profile'             => 'users#update'
  get   'users/account'             => 'users#account'
  get   'rooms/post'                => 'rooms#show_rooms'
  get   'rooms/search'              => 'rooms#search'
  post  'reservations/confirm(/id)' => 'rooms#confirm'
  post  'reservations/back'         => 'rooms#back'
  post  'reservations/complete'     => 'rooms#complete'
  get   '/reservations'             => 'rsrvs#show'

  devise_for :users, :controllers => {
    :registrations  => 'users/registrations',
    :sessions       => 'users/sessions'   
  } 
  
  resources :rooms

end

app/models/room.rb
class Room < ApplicationRecord
    mount_uploader :room_image, RoomImageUploader
    
    validates :name,          presence: true, length: { maximum: 50 }
    validates :introduction,  presence: true, length: { maximum: 255 }
    validates :price,         presence: true
    validates :address,       presence: true, length: { maximum: 255 }
    validates :room_image,    presence: true
    
    belongs_to :user
    has_many :rsrvs

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    puts @room
    if @room.save
      flash[:notice] = "部屋の登録が完了しました"  
      redirect_to @room
    else
      flash[:alert] = "必須項目を入力してください"
      render "new"
    end
  end
  
  
  def show_rooms
    @rooms = current_user.rooms
  end
  
  def show
      @room = Room.find(params[:id])
      @rsrv = Rsrv.new
  end
  
  def confirm
    @rsrv = Rsrv.new(rsrv_params)
    @room = Room.find(params[:rsrv][:room_id])
    if @rsrv.invalid?
			render "show"
		else
		  @totaldate = (@rsrv.end_date - @rsrv.start_date) / 1.days
      @rsrv.price = @totaldate * @rsrv.person_num * @room.price
    end
  end
  
  def back
    @rsrv = Rsrv.new(rsrv_params)
    @room = Room.find(params[:rsrv][:room_id])
		render "show"
  end
  
  def complete
    @rsrv = Rsrv.create!(rsrv_params)
    @room = Room.find(params[:rsrv][:room_id])
    flash[:notice] = "予約が完了しました"  
  end
  
  def search
    puts "aaaaaaaa"
    puts params[:area]
    puts params[:keyward]
    puts "aaaaaaaa"
    @rooms = Room.where("address like?", "%#{params[:area]}%").where("introduction like? or name like?", "%#{params[:keyward]}%", "%#{params[:keyward]}%")
    @count = Room.where("address like?", "%#{params[:area]}%").where("introduction like? or name like?", "%#{params[:keyward]}%", "%#{params[:keyward]}%").count
  end
  
  private

  
  def room_params
    params.require(:room).permit(:name, :introduction, :price, :address, :room_image)
  end
  
  def rsrv_params
    params.require(:rsrv).permit(:start_date, :end_date, :person_num, :user_id, :room_id, :price)
  end
  
end

app/views/rooms/complete.html.erb
<div class = "confirm-container">

  <div class = "confirm-main">
    <h3 class = "contents">予約内容確認</h3>
    
      <div class = "contents">
        <table>
          <tr class = "content">
            <th>予約した部屋</th>
            <td><%= @room.name %></td>
          </tr>
          <tr class = "content">
            <th>開始日</th>
            <td><%= @rsrv.start_date.to_s(:datetime_jp) %></td>
          </tr>
          <tr class = "content">
            <th>終了日</th>
            <td><%= @rsrv.end_date.to_s(:datetime_jp) %></td>
          </tr>
          <tr class = "content last">
            <th>価格</th>
            <td class = "price"><%= @rsrv.price %></td>
          </tr>
        </table>
      </div>
    </div>
</div>

app/views/rooms/confirm.html.erb
<div class = "confirm-container">

  <div class = "confirm-main">
    <h3 class = "content">予約内容確認</h3>
    
      <div class = "contents">
        <p class = "content"><%= @room.price %></p>
        <table>
          <tr class = "content">
            <th>開始日：</th>
            <td><%= @rsrv.start_date.to_s(:datetime_jp) %></td>
          </tr>
          <tr class = "content">
            <th>終了日：</th>
            <td><%= @rsrv.end_date.to_s(:datetime_jp) %></td>
          </tr>
          <tr class = "content">
            <th>使用日数：</th>
            <td class = "date"><%= @totaldate.to_i %></td>
          </tr>
          <tr class = "content">
            <th>人数：</th>
            <td class = "pnum"><%= @rsrv.person_num %></td>
          </tr>
          <tr class = "content last">
            <th>合計金額：</th>
            <td class = "price"><%= @rsrv.price %></td>
          </tr>
        </table>
      </div>
      <div>
        <%= form_for @rsrv, method: :post, url: reservations_complete_path do |f| %>
          <%= f.hidden_field :start_date %>
          <%= f.hidden_field :end_date %>
          <%= f.hidden_field :person_num %>
          <%= f.hidden_field :price %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit '予約を確定',class: "send-form" %>
        <% end %>
      </div>
      <div class = "back-form" >
        <%= form_for @rsrv, method: :post, url: reservations_back_path do |f| %>
          <%= f.hidden_field :start_date %>
          <%= f.hidden_field :end_date %>
          <%= f.hidden_field :person_num %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit 'ルーム詳細に戻る',class: "back-form" %>
        <% end %>
      </div>
      
      
    </div>
</div>

app/views/rooms/new.html.erb
<div class = "shows-container">
  
  <%= render "shared/aside" %>

  <div class = "shows-main">
    <h3 class = "contents">ルーム情報登録</h3>
    
    <%= form_for @room do |f| %>
      <div class = "contents">
        <%= f.label :name, class: "essential" %>
        <div class = "form">
          <%= content_tag(:div, class: ("error" if @room.errors.any? && @room.name == "" )) do  %>
            <%= f.text_field:name, :placeholder => "ルーム名", class: "text" %>
          <% end %>
        </div>
      </div>
      <div class = "contents">
        <%= f.label :introduction, class: "essential" %>
        <div class = "form">
          <%= content_tag(:div, class: ("error" if @room.errors.any? && @room.introduction == "" )) do  %>
            <%= f.text_area:introduction, :placeholder => "ルーム説明を入力", class: "text-area"%>
          <% end %>
        </div>
      </div>
      <div class = "contents">
        <%= f.label :price, class: "essential" %>
        <div class = "form">
          <%= content_tag(:div, class: ("error" if @room.errors.any? && @room.price == nil )) do  %>
            <%= f.number_field:price, :placeholder => "１日あたりの料金を入力", class: "text" %>
          <% end %>
        </div>
      </div>
      <div class = "contents">
        <%= f.label :address, class: "essential" %>
        <div class = "form">
          <%= content_tag(:div, class: ("error" if @room.errors.any? && @room.address == "" )) do  %>
            <%= f.text_field:address, :placeholder => "住所を入力", class: "text" %>
          <% end %>
        </div>
      </div>
      <div class = "contents">
        <%= f.label :room_image, class: "essential" %>
        <div class = "form">
          <%= content_tag(:div, class: ("error" if @room.errors.any? && @room.room_image == nil )) do  %>
            <%= f.file_field:room_image, accept: 'image/jpeg,image/gif,image/png' %>
          <% end %>
        </div>
      </div>
      <%= f.submit "登録", 'data-disable-with' => false, class: "update-btn" %>
      <% end %>
  </div>
</div>

app/views/rooms/search.html.erb
<div class = "search-container">

  <div class = "search-main">
    <h3 class = "contents">検索結果：<%= @count %>件</h3>
    <div class = "rooms">
      <% @rooms.each do |room| %>
        <div class = "room">
          <div class = "image">
            <%= content_tag(:a,  :href=>"#{room.id}") do %>
              <%= image_tag room.room_image.url %>
            <% end %>
          </div>
          <div class = "name">
            <%= link_to "#{room.name}", room %>
          </div>
          <div class = "address">
           <p><%= room.address %></p>
          </div>
          <div class = "price">
            <p><%= room.price %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class = "room-container">
  <div class = "room-main">
    
    <div class = "left-info">
      <div class = "room-image">
        <%= image_tag @room.room_image.url %>
      </div>
      <div>
        <div class = "icon-wrap">
          <%= image_tag current_user.image_name.url, class: "icon" %>
        </div>
        <div  class = "intro-wrap">
          <%= @room.introduction %>
        </div>
      </div>
    </div>
    <div class = "right-info">
      
      <div class = "right-cont" >
        <%= render "shared/error", obj: @rsrv %>
        
        <div class = "price content"><%= @room.price %></div>
        <%= form_for @rsrv, url: "/reservations/confirm", html: {method: "post"} do |f| %>
          <div class = "content">
            <%= f.label :start_date %>
            <%= f.date_field:start_date %>
          </div>
          <div class = "content">
            <%= f.label :end_date %>
            <%= f.date_field:end_date %>
          </div>
          <div class = "content">
            <%= f.label :person_num %>
            <%= f.number_field:person_num %>
          </div>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit "予約する", 'data-disable-with' => false, class: "rsrv-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show_rooms.html.erb
<div class = "post-container">

  <div class = "post-main">
    <h3 class = "contents">登録済みルーム一覧</h3>
    <table>
      <thead>
        <tr>
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>料金</th>
          <th>作成日</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td>
              <%= content_tag(:a,  :href=>"#{room.id}", class: "image") do %>
                <%= image_tag room.room_image.url %>
              <% end %>
            </td>
            <td><%= link_to "#{room.name}", room %></td>
            <td class = "introduction"><%= room.introduction %></td>
            <td class = "price" ><%= room.price %></td>
            <td><%= room.created_at.to_s(:datetime_jp) %></td>
          </tr>
        <% end %>
      </tbody>
    </table> 
  </div>
</div>